project:
  type: website
  resources:
      - Mansi_Budamagunta_CV.pdf

website:
  title: "Mansi Budamagunta"
  navbar:
    right:
      - href: index.qmd
        text: About
      # - about.qmd
    search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



